#Requires -Version 5.1
<#
.SYNOPSIS
    DataLink one-click installer for Windows.

.DESCRIPTION
    1. Verifies Node.js is installed
    2. Installs npm dependencies and builds both plugins
    3. Copies the PowerPoint add-in manifest to the Office sideload folder
    4. Adds the DataLink server to the Windows Startup folder so it runs
       automatically when you log in (no admin rights required)
    5. Prints InDesign load instructions

.NOTES
    Run this once from the project root:
        powershell -ExecutionPolicy Bypass -File install.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Helpers ───────────────────────────────────────────────────────────────────

function Write-Step([string]$msg) {
    Write-Host "`n$msg" -ForegroundColor Cyan
}
function Write-Ok([string]$msg) {
    Write-Host "  OK  $msg" -ForegroundColor Green
}
function Write-Fail([string]$msg) {
    Write-Host "  !!  $msg" -ForegroundColor Red
}
function Write-Info([string]$msg) {
    Write-Host "      $msg" -ForegroundColor Gray
}

# ── Locate project root ───────────────────────────────────────────────────────

$ProjectRoot = $PSScriptRoot
if (-not $ProjectRoot) {
    $ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
}
Push-Location $ProjectRoot

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  DataLink Installer" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan

# ── 1. Check prerequisites ────────────────────────────────────────────────────

Write-Step "Checking prerequisites..."

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Fail "Node.js not found."
    Write-Host ""
    Write-Host "  Please install Node.js 16+ from: https://nodejs.org" -ForegroundColor Yellow
    Write-Host "  Then re-run this installer." -ForegroundColor Yellow
    exit 1
}

$nodeVersion = node --version
Write-Ok "Node.js $nodeVersion found"

if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
    Write-Fail "npm not found (should come with Node.js)."
    exit 1
}

Write-Ok "npm found"

# ── 2. Install dependencies ───────────────────────────────────────────────────

Write-Step "Installing npm dependencies..."
npm install --silent
if ($LASTEXITCODE -ne 0) { Write-Fail "npm install failed"; exit 1 }
Write-Ok "Dependencies installed"

# ── 3. Build both plugins ─────────────────────────────────────────────────────

Write-Step "Building InDesign plugin..."
npm run build:indesign --silent
if ($LASTEXITCODE -ne 0) { Write-Fail "InDesign build failed"; exit 1 }
Write-Ok "indesign-plugin/dist/bundle.js built"

Write-Step "Building PowerPoint add-in..."
npm run build:powerpoint --silent
if ($LASTEXITCODE -ne 0) { Write-Fail "PowerPoint build failed"; exit 1 }
Write-Ok "powerpoint-addin/dist/taskpane.bundle.js built"

# ── 4. Install PowerPoint add-in manifest ────────────────────────────────────

Write-Step "Installing PowerPoint add-in..."

$wefDir = "$env:APPDATA\Microsoft\Office\16\Wef"
if (-not (Test-Path $wefDir)) {
    New-Item -ItemType Directory -Path $wefDir -Force | Out-Null
    Write-Info "Created $wefDir"
}

$manifestSrc  = Join-Path $ProjectRoot "powerpoint-addin\manifest.xml"
$manifestDest = Join-Path $wefDir "DataLink.xml"
Copy-Item -Path $manifestSrc -Destination $manifestDest -Force
Write-Ok "Manifest copied to $manifestDest"

# ── 5. Add server to Windows Startup ─────────────────────────────────────────

Write-Step "Configuring auto-start for DataLink server..."

$serveJs     = Join-Path $ProjectRoot "powerpoint-addin\serve.js"
$nodeExe     = (Get-Command node).Source
$startupDir  = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup"

# VBScript launcher — runs node silently (no console window)
$vbsContent = @"
' DataLink server auto-start
' Generated by DataLink installer — safe to delete to disable auto-start
Dim oShell
Set oShell = CreateObject("WScript.Shell")
oShell.Run """$nodeExe"" ""$serveJs""", 0, False
"@

$vbsDest = Join-Path $startupDir "DataLink-Server.vbs"
$vbsContent | Set-Content -Path $vbsDest -Encoding UTF8
Write-Ok "Auto-start script created: $vbsDest"
Write-Info "The server will start automatically at each Windows login."

# Also create a desktop shortcut so the user can start it manually right now
$desktopShortcutPath = "$env:USERPROFILE\Desktop\Start DataLink Server.lnk"
try {
    $wsh      = New-Object -ComObject WScript.Shell
    $shortcut = $wsh.CreateShortcut($desktopShortcutPath)
    $shortcut.TargetPath  = $nodeExe
    $shortcut.Arguments   = "`"$serveJs`""
    $shortcut.WorkingDirectory = (Join-Path $ProjectRoot "powerpoint-addin")
    $shortcut.Description = "Start the DataLink local server for the PowerPoint add-in"
    $shortcut.Save()
    Write-Ok "Desktop shortcut created: 'Start DataLink Server'"
} catch {
    Write-Info "Could not create desktop shortcut (non-critical): $_"
}

# Start the server now in a background window
Write-Step "Starting DataLink server now..."
Start-Process -FilePath $nodeExe -ArgumentList "`"$serveJs`"" -WindowStyle Minimized
Start-Sleep -Milliseconds 800
Write-Ok "Server started on http://localhost:3000"

# ── 6. Summary ────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  SETUP COMPLETE" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green

Write-Host ""
Write-Host "POWERPOINT ADD-IN" -ForegroundColor Cyan
Write-Host "  The DataLink server is now running at http://localhost:3000"
Write-Host "  It will auto-start every time you log into Windows."
Write-Host ""
Write-Host "  To open the add-in in PowerPoint:"
Write-Host "    1. Open PowerPoint"
Write-Host "    2. Insert tab > My Add-ins > DataLink"
Write-Host ""

Write-Host "INDESIGN PLUGIN" -ForegroundColor Cyan
Write-Host "  The plugin must be loaded once via UXP Developer Tools."
Write-Host ""
Write-Host "    1. Open InDesign CC 2021+"
Write-Host "    2. Plugins menu > UXP Developer Tools"
Write-Host "    3. Click 'Load Plugin'"
Write-Host "    4. Navigate to and select:"
Write-Host "         $ProjectRoot\indesign-plugin\manifest.json" -ForegroundColor Yellow
Write-Host "    5. The DataLink panel will appear in your panels list."
Write-Host ""

Write-Host "UNINSTALL" -ForegroundColor Cyan
Write-Host "  Delete $vbsDest to stop auto-start"
Write-Host "  Delete $manifestDest to remove the PowerPoint add-in"
Write-Host ""

Pop-Location
